import type { Finding } from './types';

export const findingsMap: Record<string, Finding> = {
  A1_muendlich: {
    id: 'A1_muendlich',
    severity: 'INDIZ',
    title: 'Mündliche Abmahnung \u2014 schwere Beweisprobleme für den Arbeitgeber',
    body: 'Eine mündliche Abmahnung ist zwar grundsätzlich wirksam (\u00A7 126 BGB findet keine Anwendung), praktisch jedoch im Streitfall kaum beweisbar. Der Arbeitgeber trägt die volle Beweislast für Inhalt und Zugang.',
    citation: 'BAG, Urt. v. 19.02.2009 \u2013 2 AZR 603/07',
  },
  A2_kein_zugang: {
    id: 'A2_kein_zugang',
    severity: 'KO',
    title: 'Abmahnung nicht zugegangen',
    body: 'Die Abmahnung ist eine empfangsbedürftige Willenserklärung. Ohne Zugang nach \u00A7 130 BGB entfaltet sie keinerlei Wirkung.',
    citation: '\u00A7 130 BGB',
  },
  A3_unzustaendig: {
    id: 'A3_unzustaendig',
    severity: 'KO',
    title: 'Unzuständige Person hat abgemahnt',
    body: 'Abmahnberechtigt sind nur Kündigungsberechtigte und Vorgesetzte mit Direktionsrecht hinsichtlich der Arbeitsleistung. Eine Abmahnung von einer nicht weisungsberechtigten Person ist unwirksam.',
    citation: 'BAG AP Nr. 3 zu \u00A7 1 KSchG 1969 Verhaltensbedingte Kündigung',
  },
  A4_unbestimmt: {
    id: 'A4_unbestimmt',
    severity: 'KO',
    title: 'Fehlende Bestimmtheit des Vorwurfs',
    body: 'Die Abmahnung enthält nur pauschale Vorwürfe. Eine wirksame Abmahnung muss das konkrete Verhalten nach Datum, Uhrzeit und Ort bezeichnen, sodass sie aus sich selbst heraus verständlich ist.',
    citation: 'BAG, Urt. v. 27.11.2008 \u2013 2 AZR 675/07',
  },
  A4_teilweise: {
    id: 'A4_teilweise',
    severity: 'INDIZ',
    title: 'Teilweise unbestimmte Vorwürfe',
    body: 'Soweit Vorwürfe pauschal bleiben, sind sie unwirksam. Zweifel gehen zu Lasten des Arbeitgebers.',
    citation: 'BAG, Urt. v. 27.11.2008 \u2013 2 AZR 675/07',
  },
  A5_keine_hinweisfunktion: {
    id: 'A5_keine_hinweisfunktion',
    severity: 'KO',
    title: 'Hinweisfunktion fehlt',
    body: 'Es ist nicht erkennbar, welche konkrete arbeitsvertragliche Pflicht verletzt worden sein soll. Die Hinweisfunktion verlangt, dass dem Arbeitnehmer der Pflichtverletzungs-Charakter seines Verhaltens deutlich gemacht wird.',
    citation: 'BAG, Urt. v. 19.04.2012 \u2013 2 AZR 258/11',
  },
  A6_keine_warnfunktion: {
    id: 'A6_keine_warnfunktion',
    severity: 'KO',
    title: 'Warnfunktion fehlt \u2014 keine Abmahnung im Rechtssinne',
    body: 'Ohne Androhung arbeitsrechtlicher Konsequenzen für den Wiederholungsfall liegt nur eine Ermahnung/Verwarnung vor. Diese kann keine Vorstufe einer verhaltensbedingten Kündigung sein.',
    citation: 'BAG, Urt. v. 19.04.2012 \u2013 2 AZR 258/11',
  },
  B1_falsch: {
    id: 'B1_falsch',
    severity: 'KO',
    title: 'Unrichtige Tatsachenbehauptung',
    body: 'Eine Abmahnung mit unzutreffendem Sachverhalt ist insgesamt aus der Personalakte zu entfernen, sofern der Arbeitgeber den Vorwurf nicht beweisen kann.',
    citation: 'BAG, Urt. v. 12.08.2010 \u2013 2 AZR 593/09',
  },
  B1_teilweise: {
    id: 'B1_teilweise',
    severity: 'INDIZ',
    title: 'Teilweise unrichtige Tatsachendarstellung',
    body: 'Soweit einzelne Vorwürfe nicht zutreffen, sind sie aus der Abmahnung zu entfernen. Bei Sammelabmahnungen führt dies zur Gesamtunwirksamkeit.',
    citation: 'BAG, Urt. v. 13.03.1991 \u2013 5 AZR 133/90',
  },
  B2_krankmeldung: {
    id: 'B2_krankmeldung',
    severity: 'KO',
    title: 'Verstoß gegen das Maßregelungsverbot \u2014 Krankmeldung',
    body: 'Die ordnungsgemäße Krankmeldung ist Ausübung eines gesetzlichen Rechts (EFZG). Eine Abmahnung wegen der Krankheit selbst verstößt gegen \u00A7 612a BGB.',
    citation: 'LAG Hessen, Urt. v. 28.03.2025 \u2013 10 SLa 916/24; \u00A7 612a BGB',
  },
  B2_br_taetigkeit: {
    id: 'B2_br_taetigkeit',
    severity: 'KO',
    title: 'Abmahnung wegen Betriebsratstätigkeit unzulässig',
    body: 'Eine individualrechtliche Abmahnung wegen reiner betriebsverfassungsrechtlicher Amtspflichtverletzungen ist nach ständiger BAG-Rechtsprechung ausgeschlossen. Sanktion ist allenfalls \u00A7 23 Abs. 1 BetrVG.',
    citation: 'BAG, Beschl. v. 09.09.2015 \u2013 7 ABR 69/13',
  },
  B2_anderes_recht: {
    id: 'B2_anderes_recht',
    severity: 'KO',
    title: 'Verstoß gegen das Maßregelungsverbot',
    body: 'Die Abmahnung sanktioniert die Ausübung eines gesetzlich geschützten Rechts und verstößt gegen \u00A7 612a BGB bzw. spezielle Maßregelungsverbote (\u00A7 5 TzBfG, \u00A7 16 AGG, \u00A7 78 S. 2 BetrVG, \u00A7 36 HinSchG).',
    citation: '\u00A7 612a BGB',
  },
  B3_kein_verschulden: {
    id: 'B3_kein_verschulden',
    severity: 'KO',
    title: 'Fehlendes Verschulden',
    body: 'Abmahnungen setzen ein steuerbares und schuldhaftes Verhalten voraus. Krankheitsbedingte Minderleistungen oder objektiv unmögliche Aufgaben sind nicht abmahnbar.',
    citation: 'BAG (st. Rspr.)',
  },
  B4_agg: {
    id: 'B4_agg',
    severity: 'KO',
    title: 'AGG-Verstoß',
    body: 'Die Abmahnung knüpft an ein Diskriminierungsmerkmal nach \u00A7 1 AGG an und verstößt gegen \u00A7\u00A7 7, 16 AGG.',
    citation: '\u00A7\u00A7 1, 7, 16 AGG',
  },
  C2_sammelabmahnung: {
    id: 'C2_sammelabmahnung',
    severity: 'KO',
    title: 'Sammelabmahnung mit unrichtigem Vorwurf',
    body: 'Die Abmahnung enthält mehrere Vorwürfe, von denen mindestens einer inhaltlich nicht zutrifft oder unkonkret bleibt. Nach gefestigter BAG-Rechtsprechung ist die gesamte Abmahnung in einem solchen Fall aus der Personalakte zu entfernen.',
    citation: 'BAG, Urt. v. 13.03.1991 \u2013 5 AZR 133/90',
  },
  D1_6_12_monate: {
    id: 'D1_6_12_monate',
    severity: 'INDIZ',
    title: 'Verzögerte Erteilung \u2014 möglicher Verwirkungseinwand',
    body: 'Zwischen Vorfall und Abmahnung liegen mehr als 6 Monate. In Verbindung mit einem Umstandsmoment kann dies zur Verwirkung nach \u00A7 242 BGB führen.',
    citation: 'LAG Nürnberg, Urt. v. 14.06.2005 \u2013 6 Sa 367/05; ArbG Mainz, Urt. v. 19.01.2023 \u2013 7 Ca 581/22',
  },
  D1_ueber_12: {
    id: 'D1_ueber_12',
    severity: 'INDIZ',
    title: 'Erhebliche Verzögerung \u2014 starkes Verwirkungsindiz',
    body: 'Eine Abmahnung mehr als 12 Monate nach dem Vorfall ist regelmäßig verwirkt, sofern kein ausdrücklicher Vorbehalt erklärt wurde.',
    citation: '\u00A7 242 BGB',
  },
  D2_verwirkung: {
    id: 'D2_verwirkung',
    severity: 'KO',
    title: 'Verwirkung nach \u00A7 242 BGB',
    body: 'Der Arbeitgeber hat durch sein Verhalten den Eindruck erweckt, der Vorgang sei erledigt. Bei einem Zeitablauf von mehr als 6 Monaten und hinzutretendem Umstandsmoment ist das Abmahnungsrecht verwirkt.',
    citation: '\u00A7 242 BGB; LAG Nürnberg 6 Sa 367/05',
  },
  E2_amtstaetigkeit: {
    id: 'E2_amtstaetigkeit',
    severity: 'KO',
    title: 'Abmahnung wegen Amtstätigkeit unzulässig',
    body: 'Reine betriebsverfassungsrechtliche Amtspflichtverletzungen rechtfertigen keine individualrechtliche Abmahnung. Sanktion ist allein \u00A7 23 Abs. 1 BetrVG.',
    citation: 'BAG, Beschl. v. 09.09.2015 \u2013 7 ABR 69/13',
  },
  E2_mischfall: {
    id: 'E2_mischfall',
    severity: 'INDIZ',
    title: 'Mischfall Amtstätigkeit / Arbeitspflicht',
    body: 'Eine Abmahnung wegen Amtspflichtverletzung mit Androhung individualrechtlicher Sanktionen ist unwirksam, sofern nicht klar getrennt wird.',
    citation: 'BAG, Beschl. v. 09.09.2015 \u2013 7 ABR 69/13',
  },
  E4_sbv_anhoerung: {
    id: 'E4_sbv_anhoerung',
    severity: 'INDIZ',
    title: 'Schwerbehindertenvertretung möglicherweise nicht angehört',
    body: 'Bei einem Bezug des Vorwurfs zur Behinderung ist die SBV gemäß \u00A7 178 Abs. 2 SGB IX vor Erteilung anzuhören (h.\u00A0M.). Bei unterlassener Anhörung droht formelle Unwirksamkeit.',
    citation: '\u00A7 178 Abs. 2 SGB IX',
  },
};
