import type { Question } from './types';

export const questions: Question[] = [
  // ── Block A — Formelle Prüfung ──
  {
    id: 'A1',
    block: 'A',
    blockLabel: 'Formelle Prüfung',
    text: 'Wurde die Abmahnung schriftlich erteilt?',
    options: [
      {
        id: 'A1_ja',
        label: 'Ja, schriftlich',
        hint: 'Indiz: wirksam',
        hintTone: 'success',
        weight: 'POSITIVE',
      },
      {
        id: 'A1_nein',
        label: 'Nein, mündlich',
        hint: 'Beweisproblem für Arbeitgeber',
        hintTone: 'warning',
        weight: 'NEGATIVE',
        triggers: ['A1_muendlich'],
      },
    ],
  },
  {
    id: 'A2',
    block: 'A',
    blockLabel: 'Formelle Prüfung',
    text: 'Ist die Abmahnung Ihnen tatsächlich zugegangen (z.\u00A0B. ausgehändigt, per Post, im Briefkasten)?',
    options: [
      {
        id: 'A2_ja',
        label: 'Ja',
        hint: 'ok',
        hintTone: 'neutral',
        weight: 'POSITIVE',
      },
      {
        id: 'A2_nein',
        label: 'Nein, ich habe sie nicht erhalten',
        hint: 'KO-Kriterium',
        hintTone: 'danger',
        weight: 'KO',
        triggers: ['A2_kein_zugang'],
      },
      {
        id: 'A2_unsicher',
        label: 'Unsicher',
        hint: 'Beweislast Arbeitgeber',
        hintTone: 'warning',
        weight: 'NEGATIVE',
      },
    ],
  },
  {
    id: 'A3',
    block: 'A',
    blockLabel: 'Formelle Prüfung',
    text: 'Von wem wurde die Abmahnung ausgesprochen?',
    options: [
      {
        id: 'A3_gf',
        label: 'Geschäftsführer / Vorstand / Personalleitung',
        hint: 'Indiz: wirksam',
        hintTone: 'success',
        weight: 'POSITIVE',
      },
      {
        id: 'A3_vorgesetzter',
        label: 'Direkter Vorgesetzter mit Weisungsbefugnis',
        hint: 'Indiz: wirksam',
        hintTone: 'success',
        weight: 'POSITIVE',
      },
      {
        id: 'A3_unbefugt',
        label: 'Eine Person ohne Weisungs- oder Personalbefugnis',
        hint: 'KO-Kriterium',
        hintTone: 'danger',
        weight: 'KO',
        triggers: ['A3_unzustaendig'],
      },
      {
        id: 'A3_unklar',
        label: 'Unklar',
        hint: 'Klärung empfohlen',
        hintTone: 'warning',
        weight: 'NEGATIVE',
      },
    ],
  },
  {
    id: 'A4',
    block: 'A',
    blockLabel: 'Formelle Prüfung',
    text: 'Beschreibt die Abmahnung das vorgeworfene Verhalten konkret nach Datum, Uhrzeit und Ort?',
    help: 'Eine wirksame Abmahnung muss aus sich selbst heraus verständlich sein. Pauschale Vorwürfe wie \u201eStörung des Betriebsfriedens\u201c genügen nicht.',
    options: [
      {
        id: 'A4_ja',
        label: 'Ja, alles konkret benannt',
        hint: 'Indiz: wirksam',
        hintTone: 'success',
        weight: 'POSITIVE',
      },
      {
        id: 'A4_nein',
        label: 'Nein, nur pauschale Vorwürfe',
        hint: 'KO-Kriterium',
        hintTone: 'danger',
        weight: 'KO',
        triggers: ['A4_unbestimmt'],
      },
      {
        id: 'A4_teilweise',
        label: 'Teilweise',
        hint: 'Starkes Indiz: unwirksam',
        hintTone: 'warning',
        weight: 'STRONG_NEGATIVE',
        triggers: ['A4_teilweise'],
      },
      {
        id: 'A4_weiss_nicht',
        label: 'Weiß ich nicht',
        hint: '',
        hintTone: 'neutral',
        weight: 'NEUTRAL',
      },
    ],
  },
  {
    id: 'A5',
    block: 'A',
    blockLabel: 'Formelle Prüfung',
    text: 'Ist aus der Abmahnung erkennbar, welche konkrete arbeitsvertragliche Pflicht verletzt sein soll?',
    options: [
      {
        id: 'A5_ja',
        label: 'Ja',
        hint: 'Indiz: wirksam',
        hintTone: 'success',
        weight: 'POSITIVE',
      },
      {
        id: 'A5_nein',
        label: 'Nein',
        hint: 'KO-Kriterium',
        hintTone: 'danger',
        weight: 'KO',
        triggers: ['A5_keine_hinweisfunktion'],
      },
      {
        id: 'A5_unklar',
        label: 'Unklar',
        hint: 'Indiz: unwirksam',
        hintTone: 'warning',
        weight: 'NEGATIVE',
      },
    ],
  },
  {
    id: 'A6',
    block: 'A',
    blockLabel: 'Formelle Prüfung',
    text: 'Wird in der Abmahnung mit Konsequenzen (z.\u00A0B. Kündigung) für den Wiederholungsfall gedroht?',
    help: 'Ohne Warnfunktion liegt nur eine Ermahnung vor \u2014 keine kündigungsrelevante Abmahnung.',
    options: [
      {
        id: 'A6_ja',
        label: 'Ja, Kündigung oder arbeitsrechtliche Konsequenzen werden angedroht',
        hint: 'Indiz: wirksam',
        hintTone: 'success',
        weight: 'POSITIVE',
      },
      {
        id: 'A6_nein',
        label: 'Nein, nur Missbilligung ohne Drohung',
        hint: 'Nur Ermahnung, keine Abmahnung',
        hintTone: 'warning',
        weight: 'STRONG_NEGATIVE',
        triggers: ['A6_keine_warnfunktion'],
      },
      {
        id: 'A6_unklar',
        label: 'Unklar',
        hint: 'Klärung empfohlen',
        hintTone: 'warning',
        weight: 'NEGATIVE',
      },
    ],
  },

  // ── Block B — Materielle Prüfung ──
  {
    id: 'B1',
    block: 'B',
    blockLabel: 'Materielle Prüfung',
    text: 'Hat das in der Abmahnung beschriebene Verhalten tatsächlich so stattgefunden?',
    options: [
      {
        id: 'B1_ja',
        label: 'Ja, vollständig',
        hint: 'ok',
        hintTone: 'neutral',
        weight: 'POSITIVE',
      },
      {
        id: 'B1_teilweise',
        label: 'Teilweise \u2014 manche Punkte stimmen nicht',
        hint: 'Starkes Indiz: unwirksam',
        hintTone: 'warning',
        weight: 'STRONG_NEGATIVE',
        triggers: ['B1_teilweise'],
      },
      {
        id: 'B1_nein',
        label: 'Nein, der Sachverhalt ist falsch',
        hint: 'KO-Kriterium',
        hintTone: 'danger',
        weight: 'KO',
        triggers: ['B1_falsch'],
      },
    ],
  },
  {
    id: 'B2',
    block: 'B',
    blockLabel: 'Materielle Prüfung',
    text: 'War das beanstandete Verhalten durch ein gesetzliches Recht gedeckt?',
    help: 'Z.\u00A0B. ordnungsgemäße Krankmeldung, Ausübung von Betriebsratstätigkeit, Whistleblowing nach HinSchG, Streikteilnahme, Inanspruchnahme von Elternzeit/Urlaub, Beschwerde nach § 84 BetrVG.',
    options: [
      {
        id: 'B2_krankmeldung',
        label: 'Ja, ordnungsgemäße Krankmeldung wird abgemahnt',
        hint: 'KO: § 612a BGB',
        hintTone: 'danger',
        weight: 'KO',
        triggers: ['B2_krankmeldung'],
      },
      {
        id: 'B2_br',
        label: 'Ja, Betriebsratstätigkeit / Amtsausübung',
        hint: 'KO: § 78 BetrVG',
        hintTone: 'danger',
        weight: 'KO',
        triggers: ['B2_br_taetigkeit'],
      },
      {
        id: 'B2_anderes',
        label: 'Ja, anderes geschütztes Recht (Elternzeit, Urlaub, Streik, Whistleblowing, Beschwerde)',
        hint: 'KO-Kriterium',
        hintTone: 'danger',
        weight: 'KO',
        triggers: ['B2_anderes_recht'],
      },
      {
        id: 'B2_nein',
        label: 'Nein',
        hint: 'ok',
        hintTone: 'neutral',
        weight: 'POSITIVE',
      },
    ],
  },
  {
    id: 'B3',
    block: 'B',
    blockLabel: 'Materielle Prüfung',
    text: 'War das Verhalten Ihnen vorwerfbar (steuerbar und schuldhaft)?',
    help: 'Krankheitsbedingte Minderleistung oder objektiv unmögliche Aufgaben sind nicht abmahnbar.',
    options: [
      {
        id: 'B3_ja',
        label: 'Ja, ich hätte mich anders verhalten können',
        hint: 'ok',
        hintTone: 'neutral',
        weight: 'POSITIVE',
      },
      {
        id: 'B3_nein',
        label: 'Nein, das Verhalten war nicht steuerbar',
        hint: 'KO-Kriterium',
        hintTone: 'danger',
        weight: 'KO',
        triggers: ['B3_kein_verschulden'],
      },
      {
        id: 'B3_unsicher',
        label: 'Unsicher',
        hint: '',
        hintTone: 'neutral',
        weight: 'NEUTRAL',
      },
    ],
  },
  {
    id: 'B4',
    block: 'B',
    blockLabel: 'Materielle Prüfung',
    text: 'Stellt die Abmahnung eine Diskriminierung im Sinne des AGG dar (Geschlecht, Alter, Religion, Behinderung, Herkunft, sex. Identität)?',
    options: [
      {
        id: 'B4_nein',
        label: 'Nein',
        hint: 'ok',
        hintTone: 'neutral',
        weight: 'POSITIVE',
      },
      {
        id: 'B4_ja',
        label: 'Ja',
        hint: 'KO: §§ 1, 7 AGG',
        hintTone: 'danger',
        weight: 'KO',
        triggers: ['B4_agg'],
      },
      {
        id: 'B4_unsicher',
        label: 'Unsicher',
        hint: 'Klärung empfohlen',
        hintTone: 'warning',
        weight: 'NEGATIVE',
      },
    ],
  },

  // ── Block C — Sammelabmahnung ──
  {
    id: 'C1',
    block: 'C',
    blockLabel: 'Sammelabmahnung',
    text: 'Werden in der Abmahnung MEHRERE unterschiedliche Pflichtverletzungen gerügt?',
    options: [
      {
        id: 'C1_ja',
        label: 'Ja, mehrere Vorwürfe',
        hint: '',
        hintTone: 'neutral',
        weight: 'NEUTRAL',
      },
      {
        id: 'C1_nein',
        label: 'Nein, nur ein Vorwurf',
        hint: 'ok',
        hintTone: 'neutral',
        weight: 'POSITIVE',
      },
    ],
  },
  {
    id: 'C2',
    block: 'C',
    blockLabel: 'Sammelabmahnung',
    text: 'Ist mindestens einer dieser Vorwürfe inhaltlich falsch oder nicht hinreichend konkretisiert?',
    showIf: (answers) => answers['C1'] === 'C1_ja',
    options: [
      {
        id: 'C2_ja',
        label: 'Ja',
        hint: 'KO: Sammelabmahnung',
        hintTone: 'danger',
        weight: 'KO',
        triggers: ['C2_sammelabmahnung'],
      },
      {
        id: 'C2_nein',
        label: 'Nein, alle Vorwürfe treffen zu und sind konkret',
        hint: 'ok',
        hintTone: 'neutral',
        weight: 'POSITIVE',
      },
      {
        id: 'C2_unsicher',
        label: 'Unsicher',
        hint: '',
        hintTone: 'warning',
        weight: 'NEGATIVE',
      },
    ],
  },

  // ── Block D — Zeitliche Prüfung ──
  {
    id: 'D1',
    block: 'D',
    blockLabel: 'Zeitliche Prüfung',
    text: 'Wie viel Zeit ist zwischen dem vorgeworfenen Verhalten und der Erteilung der Abmahnung vergangen?',
    options: [
      {
        id: 'D1_4w',
        label: 'Bis 4 Wochen',
        hint: 'ok',
        hintTone: 'neutral',
        weight: 'POSITIVE',
      },
      {
        id: 'D1_1_6',
        label: '1 bis 6 Monate',
        hint: '',
        hintTone: 'neutral',
        weight: 'NEUTRAL',
      },
      {
        id: 'D1_6_12',
        label: '6 bis 12 Monate',
        hint: 'Möglicher Verwirkungseinwand',
        hintTone: 'warning',
        weight: 'NEGATIVE',
        triggers: ['D1_6_12_monate'],
      },
      {
        id: 'D1_12plus',
        label: 'Mehr als 12 Monate',
        hint: 'Starkes Indiz: Verwirkung',
        hintTone: 'warning',
        weight: 'STRONG_NEGATIVE',
        triggers: ['D1_ueber_12'],
      },
      {
        id: 'D1_weiss_nicht',
        label: 'Weiß ich nicht',
        hint: '',
        hintTone: 'neutral',
        weight: 'NEUTRAL',
      },
    ],
  },
  {
    id: 'D2',
    block: 'D',
    blockLabel: 'Zeitliche Prüfung',
    text: 'Hat der Arbeitgeber zwischen Vorfall und Abmahnung den Eindruck erweckt, die Sache sei erledigt (z.\u00A0B. Schweigen, Lob, Bonus, klärendes Gespräch ohne Abmahnungsvorbehalt)?',
    showIf: (answers) => answers['D1'] === 'D1_6_12' || answers['D1'] === 'D1_12plus',
    options: [
      {
        id: 'D2_ja',
        label: 'Ja',
        hint: 'Verwirkungs-Konstellation',
        hintTone: 'warning',
        weight: 'STRONG_NEGATIVE',
        triggers: ['D2_verwirkung'],
      },
      {
        id: 'D2_nein',
        label: 'Nein',
        hint: '',
        hintTone: 'neutral',
        weight: 'NEUTRAL',
      },
    ],
  },

  // ── Block E — Sonderfälle ──
  {
    id: 'E1',
    block: 'E',
    blockLabel: 'Sonderfälle',
    text: 'Sind Sie Mitglied des Betriebsrats, Wahlvorstands, Sprecherausschusses oder der Schwerbehindertenvertretung?',
    options: [
      {
        id: 'E1_ja',
        label: 'Ja',
        hint: '',
        hintTone: 'neutral',
        weight: 'NEUTRAL',
      },
      {
        id: 'E1_nein',
        label: 'Nein',
        hint: '',
        hintTone: 'neutral',
        weight: 'NEUTRAL',
      },
    ],
  },
  {
    id: 'E2',
    block: 'E',
    blockLabel: 'Sonderfälle',
    text: 'Bezieht sich der Abmahnungsvorwurf auf Ihre Amtstätigkeit (z.\u00A0B. Verhalten in der BR-Sitzung, Wahrnehmung von Aufgaben nach BetrVG)?',
    showIf: (answers) => answers['E1'] === 'E1_ja',
    options: [
      {
        id: 'E2_ja',
        label: 'Ja, reine Amtstätigkeit',
        hint: 'KO: § 78 BetrVG',
        hintTone: 'danger',
        weight: 'KO',
        triggers: ['E2_amtstaetigkeit'],
      },
      {
        id: 'E2_nein',
        label: 'Nein, normale arbeitsvertragliche Pflicht',
        hint: 'ok',
        hintTone: 'neutral',
        weight: 'POSITIVE',
      },
      {
        id: 'E2_mischfall',
        label: 'Mischfall',
        hint: 'Starkes Indiz: unwirksam',
        hintTone: 'warning',
        weight: 'STRONG_NEGATIVE',
        triggers: ['E2_mischfall'],
      },
    ],
  },
  {
    id: 'E3',
    block: 'E',
    blockLabel: 'Sonderfälle',
    text: 'Sind Sie schwerbehindert oder gleichgestellt?',
    options: [
      {
        id: 'E3_ja',
        label: 'Ja',
        hint: '',
        hintTone: 'neutral',
        weight: 'NEUTRAL',
      },
      {
        id: 'E3_nein',
        label: 'Nein',
        hint: '',
        hintTone: 'neutral',
        weight: 'NEUTRAL',
      },
    ],
  },
  {
    id: 'E4',
    block: 'E',
    blockLabel: 'Sonderfälle',
    text: 'Hat der Vorwurf einen Bezug zu Ihrer Behinderung?',
    showIf: (answers) => answers['E3'] === 'E3_ja',
    options: [
      {
        id: 'E4_ja',
        label: 'Ja',
        hint: 'SBV-Anhörung prüfen',
        hintTone: 'warning',
        weight: 'NEGATIVE',
        triggers: ['E4_sbv_anhoerung'],
      },
      {
        id: 'E4_nein',
        label: 'Nein',
        hint: '',
        hintTone: 'neutral',
        weight: 'NEUTRAL',
      },
    ],
  },
];
