// Auto-generated by scripts/generate-muster-content.ts
// Do not edit manually

export interface MusterEntry {
  title: string;
  intro: string;
  muster: string;
}

export interface ChecklisteEntry {
  title: string;
  intro: string;
  punkte: string[];
}

export interface MusterContent {
  widerspruchAbmahnung: MusterEntry;
  gegendarstellungAbmahnung: MusterEntry;
  aufhebungsvertragCheckliste: ChecklisteEntry;
  abmahnungCheckliste: ChecklisteEntry;
}

export const musterContent: MusterContent = {
  "widerspruchAbmahnung": {
    "title": "Muster: Widerspruch gegen Abmahnung",
    "intro": "Ein Widerspruch gegen eine Abmahnung ist sinnvoll, wenn diese sachlich unberechtigt, unverhältnismäßig oder formal fehlerhaft ist. Nach § 83 Abs. 1 BetrVG haben Sie das Recht, sich gegen unberechtigte Beanstandungen zu wehren. Der Widerspruch dokumentiert Ihre Sicht der Dinge und kann bei einer späteren Kündigung relevant werden.",
    "muster": "[Ihr Name]\n[Straße, PLZ Ort]\n[Telefonnummer]\n[E-Mail-Adresse]\n\n[Name des Arbeitgebers]\n[Abteilung/Personalabteilung]\n[Straße, PLZ Ort]\n\n[Datum]\n\nWiderspruch gegen Abmahnung vom [Datum der Abmahnung]\n\nSehr geehrte Damen und Herren,\n\nhiermit widerspreche ich ausdrücklich der mir am [Datum der Abmahnung] erteilten Abmahnung wegen [beschriebenes Fehlverhalten].\n\nDie Abmahnung ist sachlich unberechtigt aus folgenden Gründen:\n\n1. Der mir vorgeworfene Sachverhalt entspricht nicht den Tatsachen. [Hier Ihre Darstellung der tatsächlichen Ereignisse einfügen]\n\n2. Ein Verstoß gegen arbeitsvertragliche Pflichten liegt nicht vor, da [hier Ihre rechtliche Begründung einfügen]\n\n3. Die Abmahnung ist unverhältnismäßig, weil [hier Begründung zur Verhältnismäßigkeit einfügen]\n\nIch fordere Sie daher auf, die Abmahnung aus meiner Personalakte zu entfernen und zu vernichten. Sollten Sie der Entfernung nicht nachkommen, behalte ich mir vor, rechtliche Schritte einzuleiten und beim Arbeitsgericht auf Entfernung der Abmahnung aus der Personalakte zu klagen.\n\nFür Rückfragen stehe ich gerne zur Verfügung. Ich bitte um eine schriftliche Bestätigung des Eingangs dieses Widerspruchs sowie um Mitteilung, ob Sie der Entfernung der Abmahnung nachkommen werden.\n\nMit freundlichen Grüßen\n\n[Ihre Unterschrift]\n[Ihr Name]"
  },
  "gegendarstellungAbmahnung": {
    "title": "Muster: Gegendarstellung zur Abmahnung",
    "intro": "Eine Gegendarstellung dient dazu, Ihre Sicht der Ereignisse zu dokumentieren, ohne die Abmahnung anzugreifen. Sie haben das Recht, diese Gegendarstellung zu Ihrer Personalakte nehmen zu lassen. Dies kann bei späteren arbeitsrechtlichen Auseinandersetzungen wichtig werden, um Ihre Version der Ereignisse belegen zu können.",
    "muster": "[Ihr Name]\n[Straße, PLZ Ort]\n[Telefonnummer]\n[E-Mail-Adresse]\n\n[Name des Arbeitgebers]\n[Abteilung/Personalabteilung]\n[Straße, PLZ Ort]\n\n[Datum]\n\nGegendarstellung zur Abmahnung vom [Datum der Abmahnung]\n\nSehr geehrte Damen und Herren,\n\nzu der mir am [Datum der Abmahnung] erteilten Abmahnung wegen [beschriebenes Fehlverhalten] möchte ich aus meiner Sicht wie folgt Stellung nehmen:\n\nDer Sachverhalt stellt sich aus meiner Sicht folgendermaßen dar:\n[Hier Ihre detaillierte Darstellung der Ereignisse einfügen - sachlich und chronologisch]\n\nMeine Beweggründe für mein Verhalten waren:\n[Hier Ihre Motivation und den Kontext erläutern]\n\nIch bedauere, wenn durch mein Verhalten Missverständnisse entstanden sind. Es war nicht meine Absicht, [hier entsprechende Formulierung einfügen]. In Zukunft werde ich [hier Ihre Bereitschaft zur Verbesserung/Anpassung ausdrücken].\n\nIch bitte Sie, diese Gegendarstellung zu meiner Personalakte zu nehmen, um meine Sicht der Ereignisse zu dokumentieren. Dies entspricht meinem Recht nach § 83 Abs. 1 BetrVG bzw. den allgemeinen Persönlichkeitsrechten.\n\nFür ein klärendes Gespräch stehe ich gerne zur Verfügung. Ich bin an einer konstruktiven Lösung interessiert und möchte zu einem guten Arbeitsklima beitragen.\n\nBitte bestätigen Sie mir schriftlich die Aufnahme dieser Gegendarstellung in meine Personalakte.\n\nMit freundlichen Grüßen\n\n[Ihre Unterschrift]\n[Ihr Name]"
  },
  "aufhebungsvertragCheckliste": {
    "title": "Checkliste: Aufhebungsvertrag prüfen",
    "intro": "Jeder Punkt in dieser Checkliste kann erhebliche finanzielle Auswirkungen haben und Ihre Rechte beeinflussen. Ein Aufhebungsvertrag sollte niemals voreilig unterschrieben werden. Eine anwaltliche Prüfung ist dringend empfohlen, da nachträgliche Korrekturen meist nicht möglich sind.",
    "punkte": [
      "Beendigungsdatum: Entspricht es mindestens der gesetzlichen Kündigungsfrist? Ein zu frühes Datum kostet Sie Gehalt und kann zur Sperrzeit führen.",
      "Abfindungshöhe: Ist sie angemessen? Faustformel: 0,5 Bruttomonatsgehälter pro Beschäftigungsjahr. Bei gutem Kündigungsschutz oft mehr möglich.",
      "Fälligkeit der Abfindung: Wann wird gezahlt? Vorsicht bei Ratenzahlung oder zu späten Terminen. Sofortige Zahlung ist meist besser.",
      "Freistellung: Ist sie bezahlt und unwiderruflich? Widerrufliche oder unbezahlte Freistellung verschlechtert Ihre Position erheblich.",
      "Arbeitszeugnis: Welche Note ist vereinbart? Mindestens 'gut' sollte angestrebt werden. Recht auf qualifiziertes Zeugnis prüfen.",
      "Urlaubsabgeltung: Wird der gesamte Resturlaub des laufenden Jahres abgegolten? Auch Überstunden sollten berücksichtigt werden.",
      "Wettbewerbsverbot: Bleibt es bestehen oder wird es aufgehoben? Bestehende Wettbewerbsverbote sollten gegen Karenzentschädigung aufgehoben werden.",
      "Rückgabe Firmeneigentum: Sind die Modalitäten klar geregelt? Unrealistische Fristen oder überzogene Anforderungen vermeiden.",
      "Geheimhaltungsklausel: Ist sie beidseitig oder einseitig? Einseitige Verschwiegenheitspflichten sind oft unangemessen.",
      "Sperrzeit-Formulierung: Enthält der Vertrag Formulierungen zur Vermeidung der Arbeitslosengeld-Sperrzeit? Dies ist besonders wichtig.",
      "Turbo-Klausel: Können Sie bei früherem Jobfund die Abfindung trotzdem behalten? Solche Klauseln sind vorteilhaft für Sie.",
      "Outplacement: Wird Unterstützung bei der Jobsuche angeboten? Professionelle Beratung kann sehr wertvoll sein.",
      "Betriebliche Altersvorsorge: Wie wird mit Betriebsrente oder Direktversicherung verfahren? Unverfallbare Anwartschaften sichern.",
      "Dienstwagen-Regelung: Bis wann dürfen Sie ihn nutzen? Sind Übernahme oder Abgeltung geregelt? Private Fahrten berücksichtigen.",
      "Erledigungsklausel: Sind alle Ansprüche wirklich abgegolten oder bleiben wichtige Rechte bestehen? Zu weitgehende Verzichte vermeiden."
    ]
  },
  "abmahnungCheckliste": {
    "title": "Checkliste: Abmahnung prüfen",
    "intro": "Eine formell oder inhaltlich fehlerhafte Abmahnung ist unwirksam und kann nicht als Grundlage für eine spätere Kündigung dienen. Die sorgfältige Prüfung aller Kriterien ist daher essentiell für Ihre rechtliche Absicherung und kann entscheidend für den weiteren Verlauf des Arbeitsverhältnisses sein.",
    "punkte": [
      "Konkretes Fehlverhalten benannt: Die Abmahnung muss das Fehlverhalten mit exaktem Datum, Uhrzeit und Ort beschreiben - pauschale Vorwürfe sind unwirksam.",
      "Dokumentation vollständig: Sind alle relevanten Umstände des beanstandeten Verhaltens nachvollziehbar dargestellt? Vage Beschreibungen schwächen die Abmahnung.",
      "Vertragspflicht klar benannt: Welche konkrete arbeitsvertragliche Pflicht wurde angeblich verletzt? Die Rechtsgrundlage muss erkennbar sein.",
      "Androhung von Konsequenzen: Wird ausdrücklich mit Kündigung oder anderen Maßnahmen gedroht? Ohne Androhung liegt keine wirksame Abmahnung vor.",
      "Zustellung nachweisbar: Können Sie den Erhalt der Abmahnung beweisen? Wurde sie persönlich übergeben oder ordnungsgemäß zugestellt?",
      "Verhältnismäßigkeit gewahrt: Ist die Abmahnung angemessen oder überzogen? Bei geringfügigen Verstößen kann eine Abmahnung unverhältnismäßig sein.",
      "Keine Wiederholung alter Vorwürfe: Bezieht sich die Abmahnung auf neue Ereignisse? Bereits abgemahnte oder anderweitig behandelte Vorfälle dürfen nicht erneut verwendet werden.",
      "Frist angemessen: Hatten Sie ausreichend Gelegenheit zur Stellungnahme vor Erteilung der Abmahnung? Bei schwerwiegenden Vorwürfen ist eine Anhörung erforderlich.",
      "Unterschrift berechtigt: Hat eine zur Abmahnung befugte Person unterschrieben? Nicht jeder Vorgesetzte ist automatisch zur Abmahnung berechtigt.",
      "Aufnahme in Personalakte: Wurde die Abmahnung ordnungsgemäß zur Personalakte genommen? Sie haben das Recht auf eine Kopie und können eine Gegendarstellung verlangen."
    ]
  }
};
