// Auto-generated by scripts/generate-muster-page-content.ts
// Do not edit manually

export interface GeneratedMusterPageContent {
  slug: string;
  intro: string;
  wannBenoetigt: string;
  wichtigeHinweise: string;
  ausfuellhilfe: string[];
  faqAnswers: {
    verwendung: string;
    anpassung: string;
    frist: string;
    anwalt: string;
    kosten: string;
  };
}

const data: GeneratedMusterPageContent[] = [
  {
    "slug": "widerspruch-abmahnung",
    "intro": "Ein Widerspruch gegen eine Abmahnung ermöglicht es Arbeitnehmern, unberechtigte oder unverhältnismäßige Abmahnungen zurückzuweisen. Gemäß der ständigen Rechtsprechung des BAG haben Arbeitnehmer das Recht, gegen zu Unrecht erteilte Abmahnungen zu protestieren und deren Rücknahme zu fordern. Der schriftliche Widerspruch sollte zeitnah erfolgen und die Gründe für die Zurückweisung der Abmahnung klar darlegen. Eine fundierte Gegendarstellung kann verhindern, dass die Abmahnung später als Grundlage für eine Kündigung verwendet wird.",
    "wannBenoetigt": "Ein Widerspruch ist erforderlich, wenn der Arbeitgeber dem Arbeitnehmer ein Verhalten vorwirft, das dieser nicht begangen hat oder das rechtlich nicht abmahnfähig ist. Typische Fälle sind ungerechtfertigte Vorwürfe wegen angeblicher Unpünktlichkeit, wenn tatsächlich Gleitzeit vereinbart war, oder Abmahnungen wegen Krankheit ohne nachweisbares Fehlverhalten. Auch bei unverhältnismäßigen Abmahnungen für geringfügige Verstöße, die keine Abmahnung rechtfertigen, ist ein Widerspruch angebracht. Weitere Anwendungsfälle sind fehlerhafte Tatsachenbehauptungen des Arbeitgebers oder Abmahnungen, die gegen das Maßregelungsverbot nach § 612a BGB verstoßen.",
    "wichtigeHinweise": "Für den Widerspruch gegen eine Abmahnung gibt es keine gesetzliche Frist, jedoch sollte er zeitnah erfolgen, um die Glaubwürdigkeit zu unterstreichen. Der Widerspruch muss schriftlich erfolgen und sollte konkret und sachlich die Einwände gegen die Abmahnung darlegen. Bei Betriebsräten ist zu beachten, dass diese nach § 83 BetrVG über Abmahnungen zu informieren sind und ein Mitbestimmungsrecht bei der Aufbewahrung in der Personalakte haben. Ein häufiger Fehler ist es, emotional oder unsachlich zu argumentieren, anstatt rechtliche und tatsächliche Einwände präzise zu formulieren.",
    "ausfuellhilfe": [
      "Geben Sie im Betreff und der Anrede die vollständigen Daten der zu beanstandenden Abmahnung an, einschließlich Datum und Aktenzeichen falls vorhanden.",
      "Formulieren Sie eine klare Zurückweisung der Abmahnung im ersten Absatz und fordern Sie explizit deren Rücknahme und Entfernung aus der Personalakte.",
      "Listen Sie konkret und sachlich alle Punkte auf, die Sie an der Abmahnung für unzutreffend oder unverhältnismäßig halten.",
      "Fügen Sie bei Tatsachenbehauptungen entsprechende Belege oder Zeugenaussagen bei, die Ihre Darstellung stützen.",
      "Weisen Sie auf eventuelle Verfahrensfehler hin, wie eine unterlassene Anhörung oder fehlende Beteiligung des Betriebsrats nach § 83 BetrVG.",
      "Betonen Sie bei wiederholten ungerechtfertigten Abmahnungen das Maßregelungsverbot nach § 612a BGB.",
      "Setzen Sie eine angemessene Frist für die Rücknahme der Abmahnung, üblicherweise 14 Tage ab Zugang des Widerspruchs.",
      "Verwahren Sie sich vorsorglich gegen die Verwendung der Abmahnung als Grundlage für weitere arbeitsrechtliche Maßnahmen."
    ],
    "faqAnswers": {
      "verwendung": "Das Muster bietet eine gute Grundlage für Ihren Widerspruch, sollte aber unbedingt an Ihren konkreten Fall angepasst werden. Jede Abmahnung hat individuelle Besonderheiten, die spezifisch adressiert werden müssen. Eine pauschale Übernahme ohne Anpassung kann die Wirksamkeit Ihres Widerspruchs erheblich schwächen.",
      "anpassung": "Passen Sie alle Platzhalter wie Datum, Namen und Sachverhalt an Ihren Fall an. Besonders wichtig ist die konkrete Darstellung der Gründe für Ihren Widerspruch mit spezifischen Tatsachen und rechtlichen Argumenten. Fügen Sie relevante Belege oder Zeugenaussagen hinzu und berücksichtigen Sie eventuelle betriebliche Besonderheiten.",
      "frist": "Für den Widerspruch gegen Abmahnungen gibt es keine gesetzliche Ausschlussfrist. Dennoch sollten Sie zeitnah, idealerweise innerhalb von zwei Wochen nach Erhalt der Abmahnung, widersprechen. Eine längere Wartezeit kann als stillschweigende Anerkennung der Abmahnung interpretiert werden und schwächt Ihre Position erheblich.",
      "anwalt": "Bei einfachen Sachverhalten können Sie den Widerspruch selbst verfassen, komplexere Fälle erfordern jedoch anwaltliche Unterstützung. Besonders bei rechtlich schwierigen Fragen oder wenn bereits mehrere Abmahnungen vorliegen, ist eine anwaltliche Beratung empfehlenswert. Ein Rechtsanwalt kann auch prüfen, ob zusätzlich eine Unterlassungsklage sinnvoll ist.",
      "kosten": "Eine erste Einschätzung Ihres Falls erhalten Sie bei uns kostenlos und unverbindlich. Die Kosten für eine umfassende Beratung richten sich nach dem Rechtsanwaltsvergütungsgesetz und sind abhängig vom Streitwert. Oft übernimmt die Rechtsschutzversicherung die Kosten, und bei geringem Einkommen besteht die Möglichkeit von Beratungshilfe."
    }
  },
  {
    "slug": "gegendarstellung-abmahnung",
    "intro": "Eine Gegendarstellung zur Abmahnung ist das wichtigste Mittel, um sich gegen ungerechtfertigte oder überzogene arbeitsrechtliche Vorwürfe zu wehren. Sie wird gemäß § 83 Abs. 2 BetrVG zur Personalakte genommen und stellt Ihre Sicht der Dinge dar. Eine professionell formulierte Gegendarstellung kann entscheidend sein, um späteren Kündigungen vorzubeugen und Ihre Position zu stärken. Ohne eine schriftliche Reaktion können die Vorwürfe des Arbeitgebers als unwidersprochen gelten.",
    "wannBenoetigt": "Eine Gegendarstellung benötigen Sie immer dann, wenn Sie eine Abmahnung für ungerechtfertigt oder sachlich falsch halten. Typische Situationen sind etwa Abmahnungen wegen angeblicher Arbeitszeitverstöße, die auf fehlerhaften Stundenaufzeichnungen beruhen. Auch bei Vorwürfen bezüglich Ihres Verhaltens gegenüber Kollegen oder Kunden sollten Sie widersprechen, wenn die Darstellung nicht stimmt. Weitere häufige Fälle sind Abmahnungen aufgrund unvollständiger Sachverhaltsermittlung oder wenn der Arbeitgeber überzogene Konsequenzen zieht. Selbst bei teilweise berechtigten Vorwürfen kann eine Gegendarstellung sinnvoll sein, um den Sachverhalt zu präzisieren.",
    "wichtigeHinweise": "Für eine Gegendarstellung gibt es keine gesetzliche Frist, jedoch sollten Sie zeitnah reagieren - idealerweise binnen zwei Wochen nach Erhalt der Abmahnung. Die Gegendarstellung muss schriftlich erfolgen und wird gemäß § 83 Abs. 2 BetrVG zur Personalakte genommen. Vermeiden Sie emotionale Formulierungen und persönliche Angriffe - bleiben Sie sachlich und faktenbezogen. Belegen Sie Ihre Darstellung nach Möglichkeit mit konkreten Beweismitteln wie Zeugenaussagen, E-Mails oder Dokumenten. Ein häufiger Fehler ist es, neue Vorwürfe gegen den Arbeitgeber zu erheben, anstatt sich auf die Widerlegung der Abmahnung zu konzentrieren.",
    "ausfuellhilfe": [
      "Tragen Sie das Datum der erhaltenen Abmahnung exakt ein und beziehen Sie sich konkret auf die darin erhobenen Vorwürfe",
      "Formulieren Sie Ihren Widerspruch sachlich und strukturiert - gehen Sie jeden Vorwurf einzeln durch",
      "Benennen Sie konkrete Zeugen mit vollständigen Namen und deren Bezug zum Sachverhalt, falls vorhanden",
      "Fügen Sie relevante Belege als Anlagen bei (E-Mails, Arbeitsanweisungen, Protokolle) und verweisen Sie im Text darauf",
      "Erklären Sie Ihren Standpunkt nachvollziehbar und begründen Sie, warum die Abmahnung ungerechtfertigt ist",
      "Fordern Sie konkret die Rücknahme der Abmahnung und deren Entfernung aus der Personalakte",
      "Unterschreiben Sie die Gegendarstellung handschriftlich und bewahren Sie eine Kopie für Ihre Unterlagen auf",
      "Übergeben Sie die Gegendarstellung persönlich gegen Empfangsbestätigung oder versenden Sie diese per Einschreiben"
    ],
    "faqAnswers": {
      "verwendung": "Das Muster bietet Ihnen eine strukturierte Grundlage für Ihre Gegendarstellung, muss aber individuell an Ihren Fall angepasst werden. Sie können die Formulierungen übernehmen, müssen jedoch alle konkreten Angaben zu Ihrem Sachverhalt eintragen. Prüfen Sie vor der Verwendung, ob alle Punkte auf Ihre Situation zutreffen. Eine pauschale Übernahme ohne Anpassung ist nicht empfehlenswert.",
      "anpassung": "Sie müssen alle Platzhalter mit Ihren konkreten Daten ausfüllen und die Vorwürfe spezifisch auf Ihren Fall bezogen widerlegen. Entfernen Sie Textpassagen, die nicht zu Ihrem Sachverhalt passen, und ergänzen Sie gegebenenfalls weitere relevante Punkte. Die Begründung für den Widerspruch muss individuell und detailliert ausformuliert werden. Passen Sie auch die Anlagen entsprechend Ihrer verfügbaren Beweismittel an.",
      "frist": "Für eine Gegendarstellung gibt es keine gesetzliche Ausschlussfrist, jedoch sollten Sie zügig handeln. Eine Reaktion binnen zwei Wochen nach Erhalt der Abmahnung gilt als angemessen und zeigt, dass Sie den Vorfall ernst nehmen. Bei längerer Verzögerung könnte der Eindruck entstehen, Sie akzeptieren die Abmahnung stillschweigend. Nach § 83 Abs. 2 BetrVG haben Sie das Recht, dass Ihre schriftliche Gegendarstellung zur Personalakte genommen wird.",
      "anwalt": "Bei komplexeren Sachverhalten oder wenn bereits weitere Abmahnungen vorliegen, ist anwaltliche Beratung empfehlenswert. Auch wenn Sie sich unsicher über die Berechtigung der Abmahnung sind oder eine Kündigung befürchten, sollten Sie professionelle Hilfe in Anspruch nehmen. Ein Anwalt kann die Erfolgsaussichten realistisch einschätzen und die Gegendarstellung optimal formulieren. Die Investition in eine Beratung kann sich auszahlen, wenn dadurch eine spätere Kündigung verhindert wird.",
      "kosten": "Eine erste Einschätzung zu Ihrer Abmahnung erhalten Sie bei mir kostenlos und unverbindlich. Die Kosten für eine umfassende Beratung und Erstellung einer Gegendarstellung richten sich nach dem Rechtsanwaltsvergütungsgesetz und dem Streitwert. Bei einer außergerichtlichen Tätigkeit entstehen meist überschaubare Kosten. Prüfen Sie auch, ob Ihre Rechtsschutzversicherung die Kosten übernimmt - viele Policen decken arbeitsrechtliche Streitigkeiten ab."
    }
  },
  {
    "slug": "checkliste-aufhebungsvertrag",
    "intro": "Ein Aufhebungsvertrag beendet das Arbeitsverhältnis einvernehmlich und hat weitreichende rechtliche Konsequenzen. Diese systematische Checkliste hilft Ihnen dabei, alle wichtigen Vertragspunkte zu überprüfen und mögliche Nachteile zu erkennen. Besondere Aufmerksamkeit verdienen die Sperrzeit nach § 159 SGB III und die Abfindungsregelung. Eine gründliche Prüfung vor der Unterzeichnung ist essentiell, da der Vertrag später nur schwer anfechtbar ist.",
    "wannBenoetigt": "Diese Checkliste benötigen Sie, wenn Ihr Arbeitgeber Ihnen einen Aufhebungsvertrag zur Unterzeichnung vorlegt. Typische Situationen sind betriebsbedingte Kündigungen, bei denen eine Abfindung angeboten wird, oder wenn Sie aufgrund eines Konflikts das Unternehmen verlassen sollen. Auch bei geplanten Umstrukturierungen oder Standortschließungen werden häufig Aufhebungsverträge angeboten. Selbst wenn Sie den Wechsel grundsätzlich begrüßen, sollten Sie jeden Vertrag sorgfältig prüfen, bevor Sie unterschreiben.",
    "wichtigeHinweise": "Lassen Sie sich niemals unter Zeitdruck setzen - es gibt keine gesetzliche Frist für die Entscheidung über einen Aufhebungsvertrag. Der Vertrag muss zwingend schriftlich geschlossen werden (§ 623 BGB), mündliche Vereinbarungen sind unwirksam. Achten Sie besonders auf die Sperrzeit beim Arbeitslosengeld: Ohne wichtigen Grund drohen 12 Wochen ohne Leistungen (§ 159 SGB III). Prüfen Sie alle Fristen sorgfältig, insbesondere die Kündigungsfrist und eventuelle Wettbewerbsverbote. Bei Betriebsratsmitgliedern gelten besondere Schutzvorschriften nach § 103 BetrVG.",
    "ausfuellhilfe": [
      "Vertragsparteien und Datum: Prüfen Sie, ob alle Namen und Anschriften korrekt sind und das Datum der Beendigung eindeutig feststeht. Unklarheiten können später zu Problemen bei der Arbeitsagentur führen.",
      "Beendigungszeitpunkt: Achten Sie darauf, ob die ordentliche Kündigungsfrist eingehalten wird. Eine verkürzte Frist kann zur Sperrzeit führen, außer es liegt ein wichtiger Grund vor oder der Arbeitgeber zahlt eine Entschädigung für die verkürzte Frist.",
      "Abfindungshöhe und -fälligkeit: Standard sind 0,5 Bruttomonatsgehälter pro Beschäftigungsjahr. Prüfen Sie die Berechnungsgrundlage und wann die Abfindung ausgezahlt wird - oft ist eine Zahlung nach Ablauf der Widerrufsfrist vorgesehen.",
      "Arbeitszeugnis: Bestehen Sie auf einem qualifizierten Zeugnis und lassen Sie sich die Note zusichern. Formulierungen wie 'stets zu unserer vollen Zufriedenheit' entsprechen der Note 'gut', während 'stets zu unserer vollsten Zufriedenheit' 'sehr gut' bedeutet.",
      "Resturlaub und Überstunden: Klären Sie, wie mit verbleibendem Urlaub und Mehrarbeit verfahren wird. Meist wird eine Freistellung bis zum Vertragsende vereinbart, wobei Urlaub und Überstunden abgegolten werden.",
      "Wettbewerbsverbot und Nachvertragsklauseln: Prüfen Sie, ob bestehende Wettbewerbsverbote fortgelten und ob eine Karenzentschädigung gezahlt wird. Ein nachvertragliches Wettbewerbsverbot ohne Entschädigung ist unwirksam.",
      "Ausschlussklausel und Widerruf: Viele Verträge enthalten Ausschlussfristen für weitere Ansprüche. Lassen Sie sich eine Bedenkzeit einräumen oder vereinbaren Sie ein Widerrufsrecht für einige Tage nach Vertragsschluss."
    ],
    "faqAnswers": {
      "verwendung": "Die Checkliste können Sie grundsätzlich selbstständig durchgehen, um einen ersten Überblick zu gewinnen. Sie ersetzt jedoch keine rechtliche Beratung, da jeder Fall individuelle Besonderheiten aufweist. Gerade bei komplexeren Sachverhalten oder höheren Abfindungssummen ist eine anwaltliche Prüfung empfehlenswert. Die Checkliste hilft Ihnen aber dabei, gezielt Fragen zu stellen und wichtige Punkte nicht zu übersehen.",
      "anpassung": "Wenn einzelne Punkte nicht auf Ihren Fall zutreffen, können Sie diese überspringen. Manche Aspekte wie Wettbewerbsverbote oder Firmenwagen betreffen nicht alle Arbeitnehmer. Wichtig ist, dass Sie alle für Sie relevanten Punkte sorgfältig prüfen und bei Unklarheiten nachfragen. Dokumentieren Sie, welche Punkte Sie bewusst als nicht relevant eingestuft haben.",
      "frist": "Für die Entscheidung über einen Aufhebungsvertrag gibt es keine gesetzliche Frist - lassen Sie sich nicht drängen. Anders verhält es sich mit der Schriftform: Der Vertrag muss nach § 623 BGB zwingend schriftlich geschlossen werden. Beachten Sie jedoch eventuelle Ausschlussfristen im Arbeitsvertrag für die Geltendmachung von Ansprüchen. Nach Vertragsschluss gibt es grundsätzlich kein Widerrufsrecht, es sei denn, es wurde ausdrücklich vereinbart.",
      "anwalt": "Eine anwaltliche Beratung ist besonders bei höheren Abfindungen, komplexen Vertragsklauseln oder wenn Sie unsicher sind, dringend zu empfehlen. Ein Anwalt kann den Vertrag auf versteckte Nachteile prüfen und Verbesserungen aushandeln. Oft lassen sich durch geschickte Verhandlung bessere Konditionen erzielen. Die Beratungskosten stehen meist in einem guten Verhältnis zum möglichen Mehrwert, den eine professionelle Verhandlung bringen kann.",
      "kosten": "Die Kosten für eine anwaltliche Beratung richten sich nach dem Rechtsanwaltsvergütungsgesetz und der Höhe des Streitwerts. Eine erste Einschätzung Ihres Falls biete ich kostenfrei an - so können Sie unverbindlich prüfen, ob sich eine umfassende Beratung lohnt. Bei Aufhebungsverträgen bewegen sich die Beratungskosten meist im niedrigen dreistelligen Bereich. Häufig rechtfertigt schon eine geringfügige Verbesserung der Vertragsbedingungen die Anwaltskosten."
    }
  },
  {
    "slug": "checkliste-abmahnung",
    "intro": "Diese Checkliste hilft Ihnen dabei, eine erhaltene Abmahnung systematisch auf ihre Rechtmäßigkeit zu prüfen. Eine Abmahnung ist nach §314 BGB und ständiger Rechtsprechung nur wirksam, wenn sie bestimmte formale und inhaltliche Voraussetzungen erfüllt. Viele Abmahnungen weisen Mängel auf, die ihre Wirksamkeit beeinträchtigen können. Eine sorgfältige Prüfung ist daher essentiell für Ihre weitere Verteidigung.",
    "wannBenoetigt": "Sie benötigen diese Checkliste, wenn Sie eine Abmahnung von Ihrem Arbeitgeber erhalten haben und deren Berechtigung anzweifeln. Typische Szenarien sind Abmahnungen wegen angeblicher Arbeitszeitverstöße, Krankmeldungsfehlern oder Verstößen gegen betriebliche Anweisungen. Auch bei Abmahnungen aufgrund von Konflikten mit Kollegen oder Vorgesetzten hilft eine systematische Prüfung. Besonders wichtig ist die Checkliste, wenn Sie bereits eine oder mehrere Abmahnungen erhalten haben, da eine weitere zu einer verhaltensbedingten Kündigung führen könnte.",
    "wichtigeHinweise": "Beachten Sie unbedingt die Drei-Wochen-Frist des §4 KSchG, falls die Abmahnung einer verhaltensbedingten Kündigung gleichkommt oder diese androht. Bei betriebsratspflichtigen Unternehmen ist zu prüfen, ob der Betriebsrat nach §83 BetrVG ordnungsgemäß beteiligt wurde. Häufige Fehler in Abmahnungen sind unkonkrete Vorwurfsbeschreibungen, fehlende Belege oder unverhältnismäßige Reaktionen auf geringfügige Verstöße. Dokumentieren Sie alle Umstände des gerügten Verhaltens zeitnah und sammeln Sie eventuelle Beweise oder Zeugenaussagen. Eine verspätete Abmahnung nach Monaten kann unwirksam sein, wenn der Arbeitgeber den Vorwurf zunächst hingenommen hat.",
    "ausfuellhilfe": [
      "Prüfen Sie zunächst das Datum der Abmahnung und den Zeitpunkt des gerügten Verhaltens. Eine erhebliche Verzögerung ohne plausible Begründung kann die Wirksamkeit beeinträchtigen.",
      "Kontrollieren Sie, ob der konkrete Vorwurf präzise beschrieben ist. Allgemeine Formulierungen wie 'unpünktliches Erscheinen' ohne Datum und Uhrzeit sind oft unwirksam.",
      "Überprüfen Sie die Verhältnismäßigkeit zwischen dem Vorwurf und der Abmahnung. Geringfügige Verstöße rechtfertigen meist keine Abmahnung, insbesondere bei erstmaligem Auftreten.",
      "Prüfen Sie, ob Sie zu dem Vorfall angehört wurden. Das Recht auf Stellungnahme ist grundsätzlich zu gewähren, bevor eine Abmahnung ausgesprochen wird.",
      "Kontrollieren Sie die Unterschriftsberechtigung des Abmahners. Nicht jeder Vorgesetzte ist automatisch zur Abmahnung befugt.",
      "Bei Betriebsratsbetrieben prüfen Sie, ob dieser nach §83 BetrVG ordnungsgemäß informiert oder beteiligt wurde.",
      "Dokumentieren Sie Ihre eigene Sicht der Ereignisse schriftlich und sammeln Sie Beweise oder benennen Sie Zeugen, die Ihre Version stützen können."
    ],
    "faqAnswers": {
      "verwendung": "Sie können die Checkliste durchaus selbständig durchgehen, um eine erste Einschätzung der Abmahnung zu erhalten. Die systematische Prüfung hilft dabei, mögliche Schwachstellen zu identifizieren. Bei komplexeren rechtlichen Fragen oder wenn Sie Zweifel an der Bewertung haben, sollten Sie jedoch anwaltliche Beratung in Anspruch nehmen. Eine fundierte rechtliche Einschätzung erfordert oft die Berücksichtigung individueller Umstände und aktueller Rechtsprechung.",
      "anpassung": "Wenn ein Prüfpunkt nicht auf Ihren Fall zutrifft, können Sie ihn einfach überspringen oder als 'nicht relevant' markieren. Nicht alle Abmahnungen weisen die gleichen Merkmale auf, daher ist eine flexible Anwendung der Checkliste normal. Konzentrieren Sie sich auf die für Ihren Fall relevanten Punkte und dokumentieren Sie die Gründe für das Überspringen bestimmter Aspekte. Bei Unsicherheit notieren Sie sich den Punkt für eine spätere anwaltliche Klärung.",
      "frist": "Wenn Sie gegen die Abmahnung gerichtlich vorgehen möchten, gilt grundsätzlich die allgemeine Verjährungsfrist. Bei einer Kündigung nach Abmahnung haben Sie jedoch nur drei Wochen Zeit für eine Kündigungsschutzklage nach §4 KSchG. Falls die Abmahnung selbst eine Kündigung androht oder faktisch einer Kündigung gleichkommt, sollten Sie ebenfalls die Drei-Wochen-Frist beachten. Eine schnelle Reaktion ist daher immer empfehlenswert, auch um Ihre Rechte vollständig zu wahren.",
      "anwalt": "Eine anwaltliche Beratung ist besonders dann ratsam, wenn die Abmahnung schwerwiegende Vorwürfe enthält oder Ihren Arbeitsplatz gefährdet. Auch bei bereits erfolgten Abmahnungen oder drohender Kündigung sollten Sie professionelle Hilfe in Anspruch nehmen. Die Checkliste ersetzt keine individuelle rechtliche Beratung, sondern dient der ersten Orientierung. Ein erfahrener Arbeitsrechtsanwalt kann die Erfolgsaussichten einer Gegenwehr realistisch einschätzen und die optimale Strategie entwickeln.",
      "kosten": "Eine erste telefonische oder persönliche Einschätzung Ihres Falls bieten wir kostenlos an. Die Kosten für eine ausführliche anwaltliche Beratung richten sich nach dem Rechtsanwaltsvergütungsgesetz und der Komplexität des Falls. Bei einer außergerichtlichen Vertretung entstehen meist überschaubare Kosten, die sich oft durch eine erfolgreiche Abwehr rechtfertigen. Ihre Rechtsschutzversicherung übernimmt in der Regel die Anwaltskosten im Arbeitsrecht."
    }
  }
];

export function getMusterPageContent(slug: string): GeneratedMusterPageContent | undefined {
  return data.find((d) => d.slug === slug);
}

export default data;
