import Anthropic from "@anthropic-ai/sdk";
import fs from "fs";
import path from "path";
import { musterPages, type MusterPageEntry } from "../lib/muster-data";

const client = new Anthropic();

export interface GeneratedMusterPageContent {
  slug: string;
  intro: string;
  wannBenoetigt: string;
  wichtigeHinweise: string;
  ausfuellhilfe: string[];
  faqAnswers: {
    verwendung: string;
    anpassung: string;
    frist: string;
    anwalt: string;
    kosten: string;
  };
}

async function generateForEntry(entry: MusterPageEntry): Promise<GeneratedMusterPageContent> {
  const isMuster = entry.type === "muster";

  const prompt = `Du bist ein erfahrener Fachanwalt für Arbeitsrecht in Deutschland. Erstelle Inhalte für die Seite "${entry.h1}".

Erstelle NUR das folgende JSON-Objekt, ohne Markdown-Backticks oder sonstige Formatierung:

{
  "slug": "${entry.slug}",
  "intro": "3-4 Sätze als Einleitung. Erkläre kurz, was ${isMuster ? "dieses Muster" : "diese Checkliste"} ist und warum ${isMuster ? "es" : "sie"} wichtig ist. Mit §-Referenzen wo passend. Keine Wiederholung der H1.",
  "wannBenoetigt": "4-5 Sätze. In welchen konkreten Situationen wird ${isMuster ? "dieses Muster" : "diese Checkliste"} benötigt? Nenne 3-4 typische Szenarien aus der Praxis.",
  "wichtigeHinweise": "4-5 Sätze mit konkreten rechtlichen Hinweisen. Was muss man bei ${isMuster ? "der Verwendung des Musters" : "der Prüfung"} unbedingt beachten? Fristen, Formvorschriften, häufige Fehler.",
  "ausfuellhilfe": [${isMuster ? '"6-8 konkrete Tipps als Array von Strings. Jeder Tipp erklärt, wie ein bestimmter Platzhalter oder Abschnitt auszufüllen ist. Praxisnah und verständlich."' : '"5-7 Erklärungen als Array von Strings. Jeder Punkt erklärt, worauf bei dem jeweiligen Prüfpunkt besonders zu achten ist und warum."'}],
  "faqAnswers": {
    "verwendung": "Antwort auf: ${isMuster ? "Kann ich das Muster direkt so verwenden?" : "Kann ich die Checkliste alleine durchgehen?"} (3-4 Sätze, sachlich)",
    "anpassung": "Antwort auf: ${isMuster ? "Was muss ich im Muster unbedingt anpassen?" : "Was mache ich, wenn ein Punkt nicht zutrifft?"} (3-4 Sätze, sachlich)",
    "frist": "Antwort auf: Welche Fristen muss ich beachten? (3-4 Sätze, mit §-Referenzen)",
    "anwalt": "Antwort auf: Brauche ich trotzdem einen Anwalt? (3-4 Sätze, ehrlich aber nicht abschreckend)",
    "kosten": "Antwort auf: Was kostet die anwaltliche Beratung? (3-4 Sätze, Ersteinschätzung kostenlos erwähnen)"
  }
}

Wichtig:
- Alle Texte auf Deutsch
- Professionelle aber verständliche Sprache
- §-Referenzen wo relevant (z.B. §4 KSchG, §83 BetrVG)
- NUR valides JSON zurückgeben
- Keine Markdown-Formatierung`;

  const response = await client.messages.create({
    model: "claude-sonnet-4-20250514",
    max_tokens: 4000,
    messages: [{ role: "user", content: prompt }],
  });

  const text = response.content[0].type === "text" ? response.content[0].text : "";
  const cleaned = text
    .replace(/```json\n?/g, "")
    .replace(/```\n?/g, "")
    .trim();
  return JSON.parse(cleaned);
}

async function main() {
  const outputJsonPath = path.join(process.cwd(), "lib", "generated-muster-page-content.json");
  const outputTsPath = path.join(process.cwd(), "lib", "generated-muster-page-content.ts");

  let existing: GeneratedMusterPageContent[] = [];
  if (fs.existsSync(outputJsonPath)) {
    existing = JSON.parse(fs.readFileSync(outputJsonPath, "utf-8"));
    console.log(`Found ${existing.length} existing entries — resuming.`);
  }

  const existingSlugs = new Set(existing.map((e) => e.slug));
  const remaining = musterPages.filter((e) => !existingSlugs.has(e.slug));

  if (remaining.length === 0) {
    console.log("All 5 muster page contents already generated — skipping.");
  } else {
    for (const entry of remaining) {
      console.log(`Generating: ${entry.h1}...`);
      try {
        const content = await generateForEntry(entry);
        existing.push(content);
        fs.writeFileSync(outputJsonPath, JSON.stringify(existing, null, 2), "utf-8");
        console.log(`  ✓ ${entry.slug} saved (${existing.length}/${musterPages.length})`);
      } catch (error) {
        console.error(`  ✗ Error for ${entry.slug}:`, error);
        process.exit(1);
      }
    }
  }

  const tsOutput = `// Auto-generated by scripts/generate-muster-page-content.ts
// Do not edit manually

export interface GeneratedMusterPageContent {
  slug: string;
  intro: string;
  wannBenoetigt: string;
  wichtigeHinweise: string;
  ausfuellhilfe: string[];
  faqAnswers: {
    verwendung: string;
    anpassung: string;
    frist: string;
    anwalt: string;
    kosten: string;
  };
}

const data: GeneratedMusterPageContent[] = ${JSON.stringify(existing, null, 2)};

export function getMusterPageContent(slug: string): GeneratedMusterPageContent | undefined {
  return data.find((d) => d.slug === slug);
}

export default data;
`;

  fs.writeFileSync(outputTsPath, tsOutput, "utf-8");
  console.log("✓ TypeScript saved: lib/generated-muster-page-content.ts");
  console.log("✅ All muster page content generated!");
}

main();
